name: "build"
on: [push, pull_request]
jobs:
  launch-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '17.3.0'
      - name: Dummy KV DB
        run: |
          ls
          cd code/kv_bash
          source kv.sh
          kset foo bar
          kget foo
          kget bar
      - name: Build Images
        run: |
          cd code
          chmod +x *.sh
          ./init.sh
          ./build.sh
          ./download.sh
          ./start.sh
          ./stop.sh
